### ISSUE TITLE
How do I run the tests?

### ISSUE THREAD

**Issue by MrPowers** [nvander1/spark-constraints#4]
Sorry, I'm a Mill newbie!

I tried `mill test` and `mill spark-constraints.test`.

I'm used to seeing [build.sc files in this format](https://github.com/MrPowers/mill_spark_example/blob/master/build.sc) and wasn't able to figure this out.  Thanks for the help!

**Comment by MrPowers** [comment]
BTW - so awesome that you're using building this project with Mill!

**Comment by nvander1** [comment]
Right now it’s set to cross compile for 2.11.8 and 2.12.4 . You’ve got to pass the version in as a quoted string: mill “spark-constraints[2.11.8].test”. I think the quotes are required because otherwise your shell will try to use the square brackets as a test.

I’ve got a branch trying to also include the spark version in the cross compile but I’m having issues getting that to run the test suite.

**Comment by nvander1** [comment]
@MrPowers You can now run ./scripts/test.sh from the root of the project

**Comment by MrPowers** [comment]
@nvander1 - thanks, this works on my machine.  I also notice you updated the README - good job documenting important stuff like this for other users!
